### PR TITLE
document non-obvious config setting in README

### PR DESCRIPTION
**Pull request by KentonPickard**

### CODE REVIEW

**Comment by noliar** [comment]
I think it's the feature of .NET CLI, which is not necessary to  be pointed out in the buildpack's `README`.

**Comment by KentonPickard** [comment]
It seems like my phrasing wasn't as intuitive or helpful as I had hoped.  You are right the setting is part of the .NET CLI but it is referred to in the compile script here (scroll all the way to the right):

(https://github.com/noliar/dotnet-buildpack/blob/master/bin/compile) line 126

```
PROJECT_NAME=$(ruby -rjson -e "j = JSON.parse(File.open('${PROJECT_DIR}/project.json','r:bom|utf-8').read); unless j['buildOptions'].nil? ; puts j['buildOptions']['outputName'];end")
echo "${PROJECT_NAME:=$PROJECT_DIR_NAME}"
```

For my project, I have the ASP App in the root and therefore it could not find the dll and I got an error when attempting to run on his line:

`web: cd \$HOME/heroku_output && dotnet ./${PROJECT_NAME}.dll --server.urls http://+:\$PORT ${CORE_ENVIRONMENT}`

I needed to set the output_name only in order to get this script working.  dotnet run works just fine on my local machine.

**Comment by noliar** [comment]
What's your project's structure?
 I just tested using https://github.com/noliar/ASP.NET-Core-Sample/tree/root.   No matter using `.deployment` or not, both work for me.

**Comment by KentonPickard** [comment]
I think that project deployed OK because it specifies the output name in the project.json file:

"buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true,
    "outputName": "MvcTest"
  },

I would bet if that was removed, the app would run locally with dotnet run but the deployment to heroku would fail.  

My project structure is very similar to that sample.  The yeoman tools did not specify the output name by default so I would bet someone else would run into this problem if they were to get started like that.  It would have saved me some time if the readme had mentioned needing that to be in the project and that's what I was trying to improve.  

Not a huge deal. I was able to figure it out by reading the compile script and seeing how the project name was resolved.

**Comment by noliar** [comment]
It's a bug that it gets a wrong name(always `.`) of `ROOT` project without `.deployment`. I fixed it by 8dbb180fe348e7a275440f7e6eb0146709afb758. I think another way to fix is that changing [L113](https://github.com/noliar/dotnet-buildpack/blob/master/bin/compile#L113) to `PROJECT_JSON_FILES=$(find ${SRC_DIR} -maxdepth 5 -iname "project.json")`

**Pull request closed without merging**
